advyteam-pidotnet/Presentation/Models/Usert.cs
using Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Presentation.Models
{
    public class Usert
    {
        public int id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string password { get; set; }

        
    }
}

advyteam-pidotnet/Presentation/Controllers/UsertController.cs
using Presentation.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;


namespace Presentation.Controllers
{
    public class UsertController : Controller
    {
        // GET: Usert
        public ActionResult Index()
        {

            HttpClient Client = new System.Net.Http.HttpClient();
            //Client.BaseAddress = new Uri("http://localhost:9080");
            Client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage response = Client.GetAsync("http://localhost:9080/pidev-web/api/users").Result;
            if (response.IsSuccessStatusCode)

            {
                ViewBag.result = response.Content.ReadAsAsync<IEnumerable<Usert>>().Result;


            }
            else
            {
                ViewBag.result = "error";
            }

            return View();
        }

        // GET: Usert/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Usert/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Usert/Create
        [HttpPost]
        public ActionResult Create(Usert us)
        {
            

                HttpClient Client = new HttpClient();
                HttpResponseMessage response = Client.PostAsJsonAsync<Usert>(" http://localhost:9080/pidev-web/api/users/addUser", us).ContinueWith((postTask) => postTask.Result.EnsureSuccessStatusCode()).Result;
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
            
            
            {
                return View();
            }
        }
        // GET: Usert/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Usert/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Usert/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Usert/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

advyteam-pidotnet/Presentation/Views/Usert/Create.cshtml
@model Presentation.Models.Usert

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Usert</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.firstname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.firstname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.firstname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lastname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lastname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lastname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

advyteam-pidotnet/Presentation/Views/Usert/index.cshtml
@{

    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<body>
    <!-- Page Content -->
    <div class="container">
        <div class="row">
            <button class="btn btn-primary"><a href="@Url.Action("Create","Usert")"> Add </a> </button>
           
        </div>
        <div class="col-lg-12">
            <table class="table table-bordered" >
                <thead class="thead-light">
                    <tr>
                        <th>Id</th>
                        <th>FirstName</th>
                        <th>Lastname</th>
                        <th>Email</th>
                        <th>Password</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var p in ViewBag.result)
            {
                        <tr>
                            <td>@p.id</td>
                            <td>@p.firstname</td>
                            <td>@p.lastname</td>
                            <td>@p.email</td>
                            <td>@p.password</td>


                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

   


    <script>
        $(document).ready(function () {
            $('#table_id').DataTable({

                "aLengthMenu": [[3, 5, 10, 25, -1], [3, 5, 10, 25, "All"]],
                "iDisplayLength": 5,

            });
        });
    </script>


</body>