advyteam-pidotnet/Presentation/Controllers/JobController.cs
using Data;
using Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Linq.Expressions;
using System.Net;
using Presentation.Models;
using System.Web.UI.WebControls;
using System.IO;
using System.Web.UI;

namespace Presentation.Controllers
{
    public class JobController : Controller
    {
        IJob ir = new JobService();
        Iutilisateurser aa = new utilisateurser();
        ISkillsService skills = new SkillsService();

        // GET: Job
        public ActionResult Index()
        {
            List<skills> ski = skills.GetMany().ToList();
            List<job> jobs = ir.GetMany().ToList();
            foreach (var item in jobs)
            {

                foreach (var item1 in ski)
                {
                    if (item.idskill == item1.idskill)
                    {
                        item.skills.skillsname = item1.skillsname;
                    }
                }

            }


                return View(jobs);
        }


        [HttpPost]
        public ActionResult setJobDetail(String competencedef, String department, String description, int level , String nom, int user_id)
        {
            job e = new job();
            e.competencedef = competencedef;
            e.description = description;
            e.department = department;
            e.nom = nom;
            e.level = level;
            //  e.Condidat = 1;

            return View(e);
        }



        // GET: Job/Details/5
        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            job job = ir.GetById(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        // GET: Job/Create
        public ActionResult Create()
        {
            var cat = aa.GetMany();
            var cat2 = skills.GetMany();
            JobModel pm = new JobModel();
            pm.utilisateurs = cat.Select(p => new SelectListItem
            {
                Text = p.Name,
                Value = p.cin.ToString()
            });
            pm.listSkills = cat2.Select(p => new SelectListItem
            {
                Text = p.skillsname,
                Value = p.idskill.ToString()
            });
            return View(pm);
        }

        // POST: Job/Create
        [HttpPost]
        public ActionResult Create(JobModel pm)
        {
            try
            {
                // TODO: Add insert logic here
                job p = new job();
                p.nom = pm.nom;
                p.description = pm.description;
                p.department = pm.department;
                p.competencedef = pm.competencedef;
                p.cin = pm.cin;
                p.idskill = pm.idskill;

                ir.Add(p);
                ir.Commit();
                
                
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }


        }

        // GET: Job/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Job/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, job r)
        {
            if (ModelState.IsValid)
            {
                if (id == null)
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                job recFromDB = ir.GetById(id);
                r.competencedef = recFromDB.competencedef;
                r.description = recFromDB.description;
                r.department = recFromDB.department;
                r.nom = recFromDB.nom;
                r.level = recFromDB.level;
                ir.Update(r);
                ir.Commit();


            }
            return RedirectToAction("Index");
        }

        // GET: Job/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Job/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            job r;
            r = ir.GetById(id);

            ir.Delete(r);
            ir.Commit();
            // es.Dispose();

            return RedirectToAction("Index");
        }


        [HttpPost]
        public JsonResult GetStat()
        {


            var dt = ir.GetMany().GroupBy(a => a.department)
                        .Select(g => new { g.Key, Count = g.Count() });
            return new JsonResult { Data = dt };


        }

        public ActionResult ExportData()
        {
            var datasource = ir.GetMany().ToList();

            GridView gv = new GridView();
            gv.DataSource = datasource;
            gv.DataBind();
            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment; filename=Report.xls");
            Response.ContentType = "application/ms-excel";
            Response.Charset = "";
            StringWriter sw = new StringWriter();
            HtmlTextWriter htw = new HtmlTextWriter(sw);
            gv.RenderControl(htw);
            Response.Output.Write(sw.ToString());
            Response.Flush();
            Response.End();

            return Json("Success");
        }

    }
}

advyteam-pidotnet/Presentation/Views/Job/Create.cshtml
@model Presentation.Models.JobModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">


    <!-- Bootstrap core CSS -->
    <link href="~/Content/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

</head>



<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>JobModel</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.competencedef, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.competencedef, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.competencedef, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.department, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.department, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.department, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.level, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.level, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.level, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.nom, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.nom, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.nom, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.cin, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.cin, Model.utilisateurs)
                    @Html.ValidationMessageFor(model => model.cin)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.idskill, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.idskill, Model.listSkills)
                    @Html.ValidationMessageFor(model => model.idskill)
                </div>
            </div>


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

   
</body>

advyteam-pidotnet/Presentation/Views/Job/Delete.cshtml
@model Data.job

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>job</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.competencedef)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.competencedef)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.department)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.department)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.level)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.level)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.user_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.user_id)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

advyteam-pidotnet/Presentation/Views/Job/Details.cshtml
@model Data.job

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
}

<h2>Details</h2>

<div>
    <h4>job</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.competencedef)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.competencedef)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.department)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.department)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.level)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.level)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nom)
        </dd>

       

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

advyteam-pidotnet/Presentation/Views/Job/Edit.cshtml
@model Data.job

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>job</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.competencedef, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.competencedef, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.competencedef, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.department, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.department, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.department, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.level, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.level, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.level, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.user_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.user_id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.user_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

advyteam-pidotnet/Presentation/Views/Job/ExportData.cshtml
@model Presentation.Models.JobModel

@{
    ViewBag.Title = "ExportData";
}

<h2>ExportData</h2>

advyteam-pidotnet/Presentation/Views/Job/Index.cshtml
@model IEnumerable<Data.job>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Index</h2>

@using (Html.BeginForm("ExportData", "Job", FormMethod.Post))
{

    <button type="Submit">Export to Excel</button>
}

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">


    <!-- Bootstrap core CSS -->
    <link href="~/Content/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

</head>

<p>
    @Html.ActionLink("Create New", "Create")
</p>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.competencedef)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.department)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.level)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nom)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.skills.skillsname)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.competencedef)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.department)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.level)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.skills.skillsname)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                @Html.ActionLink("Details", "Details", new { id = item.id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.id })
            </td>
        </tr>
    }

</table>

<div id="chartc">
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>



<script type="text/javascript">

    var data;
    $.ajax({
        type: "POST",
        url: "http://localhost:22631/Job/GetStat",
        dataType: 'json',
        success: function (Data) {

            var tb = [];
            //ds = JSON.parse(Data);
            $.each(Data, function (index, key) {
                console.log(key.Key);
                t = [key.Key, key.Count];
                tb.push(t);
            });
            console.log(tb);

            Highcharts.chart('chartc', {
                chart: {
                    plotBackgroundColor: null,
                    plotBorderWidth: null,
                    plotShadow: false,
                    type: 'pie'
                },
                title: {
                    text: 'Statistique des JOB selon département'
                },
                tooltip: {
                    pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
                },
                plotOptions: {
                    pie: {
                        allowPointSelect: true,
                        cursor: 'pointer',
                        dataLabels: {
                            enabled: true,
                            format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                            style: {
                                color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                            }
                        }
                    }
                },
                series: [{
                    name: 'Brands',
                    colorByPoint: true,
                    data: tb
                }]
            })




        }
        ,
        error: function (error) {
            console.log(error);
        }
    });









</script>

advyteam-pidotnet/Presentation/Views/Job/setJobDetail.cshtml
@model Data.job
@{
    ViewBag.Title = "setJobDetail";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<div>
    <h4>Reclamation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.competencedef)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.competencedef)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.department)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.department)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.level)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.level)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nom)
        </dd>

      

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>